server:
  port: 8886
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: client-b
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:2222
    enabled: true