eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8880
#  port: 8881
#  port: 8882
spring:
  application:
    name: client-a
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:2222
    enabled: true